version: "3"

services:

  localstack:
    image: localstack/localstack:3.7.2
    container_name: edpoc-localstack
    ports:
      - '4566:4566'
      - '${PORT_WEB_UI-8010}:${PORT_WEB_UI-8080}'
    environment:
      - SERVICES=sqs,sns
      - DEBUG=${DEBUG-''}
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=ap-southeast-1
    volumes:
      - localstack-dataVolume:/tmp/localstack-vol

volumes:
  localstack-dataVolume: